volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_tor_data: {}
  production_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: hodlwatcher_production_django
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    # Añadir DNS para el servicio base django
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: hodlwatcher_production_postgres
    restart: always
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: hodlwatcher_production_traefik
    restart: always
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:81:81'
      - '0.0.0.0:443:443'
      - '0.0.0.0:5555:5555'

  redis:
    image: docker.io/redis:6
    restart: always
    volumes:
      - production_redis_data:/data

  celeryworker:
    <<: *django
    image: hodlwatcher_production_celeryworker
    restart: always
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: hodlwatcher_production_celerybeat
    restart: always
    command: /start-celerybeat

  flower:
    <<: *django
    image: hodlwatcher_production_flower
    restart: always
    command: /start-flower

  telegram:
    build:
      context: .
      dockerfile: ./compose/production/telegram/Dockerfile
    image: hodlwatcher_production_telegram
    restart: always
    depends_on:
      - postgres
      - redis
      - django
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    # Añadir configuración DNS específica para telegram
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: /start-telegram

  # awscli:
  #   build:
  #     context: .
  #     dockerfile: ./compose/production/aws/Dockerfile
  #   env_file:
  #     - ./.envs/.production/.django
  #   volumes:
  #     - production_postgres_data_backups:/backups:z

  tor:
    build:
      context: .
      dockerfile: ./compose/production/tor/Dockerfile
    image: hodlwatcher_production_tor
    restart: always
    depends_on:
      - traefik
    volumes:
      - production_tor_data:/var/lib/tor