# Generated by Django 5.1.8 on 2025-04-29 10:55

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('name_es', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría de FAQ',
                'verbose_name_plural': 'Categorías de FAQ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Pregunta')),
                ('question_en', models.CharField(max_length=255, null=True, verbose_name='Pregunta')),
                ('question_es', models.CharField(max_length=255, null=True, verbose_name='Pregunta')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Respuesta')),
                ('answer_en', ckeditor.fields.RichTextField(null=True, verbose_name='Respuesta')),
                ('answer_es', ckeditor.fields.RichTextField(null=True, verbose_name='Respuesta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('related_questions', models.ManyToManyField(blank=True, related_name='related_to', to='faq.faq', verbose_name='Preguntas relacionadas')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='faq.faqcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Pregunta Frecuente',
                'verbose_name_plural': 'Preguntas Frecuentes',
                'ordering': ['order'],
            },
        ),
    ]
