# Generated by Django 5.1.8 on 2025-04-30 15:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_fr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Respuesta'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Pregunta'),
        ),
        migrations.AddField(
            model_name='faqcategory',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
