# Generated by Django 5.1.8 on 2025-04-29 10:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Your Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+99999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,17}$')], verbose_name='Phone Number')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Your Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('recibir_alertas_watchdog', models.BooleanField(default=False)),
                ('rate_fee', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentWatchdog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='sell', max_length=4)),
                ('rate_fee', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Rate Fee (%)')),
                ('payment_method_id', models.CharField(default='51', max_length=6)),
                ('amount', models.PositiveIntegerField()),
                ('asset_code', models.CharField(default='BTC', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchdogs', to=settings.AUTH_USER_MODEL)),
                ('usuario_telegram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchdogs', to='app.usuariotelegram')),
            ],
            options={
                'verbose_name': 'Watchdog',
                'verbose_name_plural': 'Watchdogs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile.png', upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_telegram', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.usuariotelegram')),
            ],
        ),
        migrations.CreateModel(
            name='WatchdogNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=100)),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('offer_details', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('watchdog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.investmentwatchdog')),
            ],
            options={
                'verbose_name': 'Notificación de Watchdog',
                'verbose_name_plural': 'Notificaciones de Watchdog',
                'unique_together': {('watchdog', 'offer_id')},
            },
        ),
    ]
